spring.application.name=gateway-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/sahayak
spring.datasource.username=sahayak
spring.datasource.password=Sahayak@1234
spring.jpa.hibernate.ddl-auto=update
#spring.security.oauth2.client.registration.google.client-id=your-client-id
#spring.security.oauth2.client.registration.google.client-secret=your-client-secret
twilio.accountSid=AC5c1dde32b9e3725ea6fcb03877e9fa7e
twilio.phoneNumber=+13412446478
twilio.authToken=dea7a29e8050a6e5bd5262c409fe9fbe
file.upload-dir=uploads/assets
server.base-url=http://localhost:8081
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
kafka.topic.campaign-created=campaign-created
vwoy dciw eedh uvla
spring.cache.type=redis
service-communication-api-key="jb4j3b78dgbv278rtrwvf78t23vb"

// Google OAuth2 Configuration
google.client-id=639931170277-d0tprb69ckru8r34pspujdncmu8o96mf.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://localhost:8081/api/v1/auth/google/callback
google.token-uri=https://oauth2.googleapis.com/token
google.userinfo-uri=https://www.googleapis.com/oauth2/v2/userinfo


// OpenAI Configuration
openai.api-key=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
openai.api-base-url-chat-completion=https://api.openai.com/v1/chat/completions

//Gemini Configuration
gemini.api-key=AIzaSyBIGRASCZVus4qEELLKSMH_Wq8hr_vSU4I
gemini.api-base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
